; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = seeed_xiao_esp32c3

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps = 
	robotis-git/Dynamixel2Arduino@^0.7.0
build_src_filter = +<main.cpp>

[env:replace_id18]
extends = env:seeed_xiao_esp32c3
build_src_filter = +<replace_id18.cpp>

[env:align_id18]
extends = env:replace_id18
build_flags = -DQ8_ENABLE_ALIGNMENT
