[platformio]
default_envs = seeed_xiao_esp32c3

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps = robotis-git/Dynamixel2Arduino@^0.7.0

[env:id18_test]
extends = env:seeed_xiao_esp32c3
build_flags = -DQ8_ENABLE_ID18_TEST

[env:id16_test]
extends = env:seeed_xiao_esp32c3
build_flags = -DQ8_ENABLE_ID18_TEST -DQ8_TEST_ID=16
